# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('release_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tags', django_extensions.db.fields.json.JSONField(null=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release_dashboard.Project')),
            ],
        ),
    ]
