# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('release_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='release_dashboard.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DockerTag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manifests', django_extensions.db.fields.json.JSONField()),
                ('image', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='release_dashboard.DockerImage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dockertag',
            unique_together=set([('name', 'image')]),
        ),
    ]
