# Generated by Django 3.1.14 on 2022-01-19 08:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("release_dashboard", "0003_dockertag_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockertag",
            name="manifests",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="json_branches",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="json_tags",
            field=models.JSONField(null=True),
        ),
    ]
