default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        exclude: >
            (?x)^(
                migrations/.*|
                .*/conf.py
            )$
        args: ["--py37-plus"]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
    -   id: eslint
        args: ['--fix']
        exclude: >
            (?x)^(
                .*min\.js|
                panel/static/panel/js/jquery*\.js|
                panel/static/panel/js/npm\.js|
                panel/static/panel/js/bootstrap\.js|
            )$
        additional_dependencies:
        -   eslint-config-jquery
