default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    -   id: reorder-python-imports
        exclude: migrations/
        args: ["--py37-plus"]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
    -   id: requirements-txt-fixer
