---
- hosts: all
  connection: local
  sudo: True
  sudo_user: root
  tasks:
    - name: install Debian package requirements
      apt: name=libyaml-dev state=present
      apt: name=python3-dev state=present
      apt: name=python3-venv state=present

- hosts: all
  connection: local
  tasks:
    - name: deploy
      shell: |
        make deploy
