[tool.black]
line-length = 79
py37 = true
exclude = '''
/(
  migrations
  | __pycache__
)/
'''
[tool.pytest.ini_options]
#FAIL_INVALID_TEMPLATE_VARS = true
django_debug_mode = true
DJANGO_SETTINGS_MODULE = "repoapi.settings.test"
pep8ignore = "*.py W503"
[tool.coverage.run]
data_file = "/results/.coverage"
omit = [
  "*/test/*",
  "*/test_*.py",
]