# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-09 09:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReleaseChanged",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                (
                    "vmtype",
                    models.CharField(
                        choices=[("CE", "spce"), ("PRO", "sppro")],
                        max_length=3,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ABORTED", "ABORTED"),
                            ("FAILURE", "FAILURE"),
                            ("NOT_BUILT", "NOT_BUILT"),
                            ("SUCCESS", "SUCCESS"),
                            ("UNSTABLE", "UNSTABLE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="releasechanged", unique_together=set([("version", "vmtype")])
        ),
    ]
