# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-30 11:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("release_changed", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="releasechanged",
            name="label",
            field=models.CharField(default="daily", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="releasechanged",
            name="vmtype",
            field=models.CharField(
                choices=[
                    ("CE", "spce"),
                    ("PRO", "sppro"),
                    ("CARRIER", "carrier"),
                ],
                max_length=7,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="releasechanged",
            unique_together=set([("version", "vmtype", "label")]),
        ),
    ]
