# Generated by Django 3.2.15 on 2022-12-15 15:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("builton", models.CharField(max_length=50)),
                ("timestamp", models.PositiveBigIntegerField()),
                ("duration", models.PositiveSmallIntegerField()),
                ("projectname", models.CharField(max_length=100)),
                ("buildnumber", models.IntegerField()),
                ("jobname", models.CharField(max_length=100)),
                (
                    "param_tag",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "param_branch",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "param_release",
                    models.CharField(db_index=True, max_length=50, null=True),
                ),
                (
                    "param_release_uuid",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "param_distribution",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "param_ppa",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
