# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapi', '0007_auto_20160718_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenkinsbuildinfo',
            name='release_uuid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterIndexTogether(
            name='jenkinsbuildinfo',
            index_together=set([
                ('release_uuid', 'tag'),
                ('param_release', 'projectname', 'tag'),
                ('param_release', 'projectname')
            ]),
        ),
    ]
