# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-10 14:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("repoapi", "0009_allow_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="gerritrepoinfo",
            name="projectname",
            field=models.CharField(default="unknown", max_length=100),
            preserve_default=False,
        ),
    ]
