# Generated by Django 3.2.15 on 2022-09-13 17:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("repoapi", "0012_ldap_grp_perms"),
    ]

    operations = [
        migrations.CreateModel(
            name="MantisNoteInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mantis_id", models.CharField(max_length=50)),
                ("gerrit_change", models.CharField(max_length=50)),
                ("eventtype", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {
                    ("mantis_id", "gerrit_change", "eventtype")
                },
            },
        ),
    ]
