# Generated by Django 3.2.17 on 2023-03-02 07:22
import datetime

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repoapi", "0014_fix_jbi_gerrit"),
    ]

    operations = [
        migrations.AddField(
            model_name="gerritrepoinfo",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=datetime.datetime(1977, 1, 1, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gerritrepoinfo",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True
            ),
        ),
    ]
