# Generated by Django 3.2.15 on 2022-09-13 08:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("hotfix", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MantisNoteInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectname", models.CharField(max_length=50)),
                ("version", models.CharField(max_length=50)),
                ("mantis_id", models.CharField(max_length=50)),
            ],
            options={
                "unique_together": {("mantis_id", "projectname", "version")},
            },
        ),
    ]
