# Generated by Django 3.2.15 on 2022-09-15 06:57
from django.db import migrations
from django.db import models

import tracker.conf


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackermapper",
            name="mapper_type",
            field=models.CharField(
                choices=[
                    (tracker.conf.MapperType["ISSUE"], "Issue"),
                    (tracker.conf.MapperType["TASK"], "Task"),
                ],
                max_length=50,
            ),
        ),
    ]
